spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: kostya
    hibernate:
      ddl-auto: validate
  flyway:
    schemas: kostya
server:
  error:
    include-message: always
springdoc:
  swagger-ui:
    operations-sorter: method
