spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: kostya
    hibernate:
      ddl-auto: none
  flyway:
    baseline-on-migrate: true
    default-schema: kostya