CREATE TABLE boards (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(32),
    description text,
    created_at timestamp(6),
    updated_at timestamp(6)
);

CREATE TABLE cards (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id bigint references boards(id) on delete cascade,
    name varchar(32),
    description text,
    created_at timestamp(6),
    updated_at timestamp(6)
);

